[project]
name = "automation-basic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.4",
    "poethepoet>=0.33.1",
    "pytest>=8.3.5",
    "ruff>=0.11.6",
    "sphinx-automodapi>=0.18.0",
    "sphinx-rtd-theme>=3.0.2",
    "sphinx>=8.2.3",
    "sphinxcontrib-bibtex>=2.6.3",
]

[tool.poe.tasks]
html.shell = "rm -fr docs/build && uv run sphinx-build -M html docs/source docs/build"
api-rst.shell = "rm -fr docs/source/api && uv run sphinx-apidoc -o docs/source/api automation_basics/"
test-demo.shell = "pytest -vs --junitxml=test-results/$(date '+%F_s%s').xml automation_basics/test_demo/ "

[project.scripts]
simple = "automation_basics.simple_functions.main:main"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.hatch.build.targets.wheel]
packages = ["automation_basics"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
